### ISSUE TITLE
Install Sprout Reports fails on DB error

### ISSUE THREAD

**Issue by johnwbaxter** [barrelstrength/craft-sprout-reports#126]
### Description (screenshots, logs, ...)

We had Sprout Reports in the site but then we needed to update it and Sprout was causing the update to fail so we removed it, ran the updates and now want to add it back but we keep getting a db error

### Steps to reproduce

1. composer require barrelstrength/sprout-reports
2. See error "Invalid datatime format: 1292 Truncated incorrect DOUBLE value: 'sproutreports.users'"

### Additional info

I have deleted all data out the old tables, I've removed the old tables, nothing I do stops this happening!

- Craft version: 3.5
- PHP version: 7.3
- Database driver & version:  mysql 5.7
- Plugins & versions: 1.5.13

**Comment by BenParizek** [comment]
Hey @johnwbaxter 

Are you able to update to the latest version of Craft? I believe the issue here has to do with composer dependencies.

Sprout Reports shares it's report module with other Sprout plugins, and in the mid 3.x series of releases there is a scenario where Sprout Reports can pull in a future version of the reports module where the schema has changed.

There are two ways to approach this:

1) Update to the latest, as we have released a fix but it is only present if you get upgraded far enough
2) Look up all the Sprout Reports dependencies and hard code the ones that were available at the time at the Craft release you are trying to update to, and then remove those dependencies from your composer at some point in the future when you want to revert back to the normal upgrade path.

To achieve #2 you'll want to look up the release date of the Craft version you need to be on, and find the release for the matching time frame in Sprout Reports and lock in the versions of the specific dependency releases in your main composer file. As an example, here are the two dependencies and their version numbers for the current release.

https://github.com/barrelstrength/craft-sprout-reports/blob/c97807873fb3806765c0912391b1b92f8e005926/composer.json#L29-L30

Feel free to follow up with more specific questions about the exact release you're trying to get updated to if you have any follow up questions.

**Comment by johnwbaxter** [comment]
@BenParizek I worked round it in the end by bringing the site forward on some other updates and then retrying. Thanks!
