### ISSUE TITLE
Exception 'Error' with message 'Class 'barrelstrength\sproutbase\app\reports\services\DataSources' not found'

### ISSUE THREAD

**Issue by billymedia** [barrelstrength/craft-sprout-reports#55]
### Description
Out the blue, loading the site up is resulting in the following error:

`Exception 'Error' with message 'Class 'barrelstrength\sproutbase\app\reports\services\DataSources' not found'
`
in vendor/barrelstrength/sprout-forms/src/SproutForms.php line 126

I would like to try and update the plugins but due to the error, i cannot do this.

### Steps to reproduce

1. Anything, it happens in the control panel, front end, cli

### Additional info

- Craft version: 3.1.5
- PHP version: 7.1.26
- Plugins & versions: Reports - 1.1.1, Forms - 3.0.0-beta.37

**Comment by BenParizek** [comment]
@billymedia More recent versions of our plugins have moved the file that you are seeing not found. So the issue has likely arisen because one plugin was somehow updated to a newer version along with its dependencies, without the other plugin also getting updated. 

If you want to share your `composer.json` file I can be more specific with an answer. 

In general, following the steps outlined here should help get things updated and resolved:
https://craftcms.stackexchange.com/a/30535/115

**Comment by billymedia** [comment]
Thanks @BenParizek The SE link fixed it.
